// docs/examples/examples/svelte/ImageBlock.svelte
<script>
  import { getImageUrl } from './utils.js';
  export let block;
  $: href = block.href?.[0]?.['@id'] || block.href;
  $: imgSrc = getImageUrl(block.url);
</script>

<!-- No image ⇒ no element. While editing, Inka hands an empty image a
     stand-in to click; a visitor sees nothing. -->
<div data-block-uid={block['@uid']}>
  {#if imgSrc && href}
    <a {href} data-edit-link="href">
      <img data-edit-media="url" src={imgSrc} alt={block.alt} />
    </a>
  {:else if imgSrc}
    <img data-edit-media="url" src={imgSrc} alt={block.alt} />
  {/if}
</div>

// docs/examples/examples/react/ImageBlock.jsx
import { getImageUrl } from './utils.js';

function ImageBlock({ block }) {
  const src = getImageUrl(block.url);
  const alt = block.alt || '';
  const href = block.href?.[0]?.['@id'] || block.href;

  // No image ⇒ no element. While editing, Inka hands an empty image a
  // stand-in to click; a visitor sees nothing.
  if (!src) return <div data-block-uid={block['@uid']} />;
  const img = <img data-edit-media="url" src={src} alt={alt} />;

  return (
    <div data-block-uid={block['@uid']}>
      {href ? (
        <a href={href} data-edit-link="href">{img}</a>
      ) : (
        <>{img}</>
      )}
    </div>
  );
}
