// docs/examples/examples/svelte/ImageBlock.svelte
<script>
  import { getImageUrl } from './utils.js';
  export let block;
  $: href = block.href?.[0]?.['@id'] || block.href;
  $: imgSrc = getImageUrl(block.url);
</script>

<!-- No image ⇒ no element. While editing, Inka hands an empty image a
     stand-in to click; a visitor sees nothing. -->
<div data-block-uid={block['@uid']}>
  {#if imgSrc && href}
    <a {href} data-edit-link="href">
      <img data-edit-media="url" src={imgSrc} alt={block.alt} />
    </a>
  {:else if imgSrc}
    <img data-edit-media="url" src={imgSrc} alt={block.alt} />
  {/if}
</div>

// docs/examples/examples/vue/ImageBlock.vue
<template>
  <div :data-block-uid="block['@uid']">
    <!-- No image ⇒ no element. While editing, Inka hands an empty image a
         stand-in to click; a visitor sees nothing. -->
    <template v-if="imgSrc">
      <a v-if="href" :href="href" data-edit-link="href">
        <img data-edit-media="url" :src="imgSrc" :alt="block.alt" />
      </a>
      <img v-else data-edit-media="url" :src="imgSrc" :alt="block.alt" />
    </template>
  </div>
</template>

<script setup>
import { computed } from 'vue';
import { getImageUrl } from './utils.js';
const props = defineProps({ block: Object });
const href = computed(() => props.block.href?.[0]?.['@id'] || props.block.href);
const imgSrc = computed(() => getImageUrl(props.block.url));
</script>
